name: tensorflow_cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - scikit-learn
  - scipy
  - pandas
  - pandas-datareader
  - matplotlib
  - pillow
  - tqdm
  - requests
  - h5py
  - pyyaml
  - flask
  - boto3
  - pip
  - pip:
      - tensorflow-cpu
